[package]
name = "rust-language"
version = "0.1.0"
authors = ["Qingyu Deng <i@ayase-lab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
